[package]
name = "bright"
version = "0.0.1"
edition = "2024"

[dependencies]
calibright = "0.1.11"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
futures-util = { version = "0.3.31", features = ["alloc"] }

